# -*- coding: utf-8 -*-
"""asos_reader.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DCgRH7ugotr1uRnM6wIsFgxfcj9U5_T3
"""

#### 3 processing.py
# processing analysis functions

def word_counter(ls):
    nameDict = {}
    for i in ls:
        if isinstance(i,str):
            strarr = i.split()
            for word in strarr:
                if word in nameDict.keys():
                    nameDict[word] += 1
                else:
                    nameDict[word] = 1

    ordNameDict= sorted(nameDict.items(), key=lambda x: x[1], reverse=True)
    return ordNameDict
